# Generated by Django 5.0 on 2023-12-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30)),
                ('year_production', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=25)),
            ],
        ),
    ]
